<?php
require_once 'session.php';
require_once 'db_connect.php';
require_once 'log_activity.php'; // Include the logging helper

// Check if user is logged in
if (!isset($_SESSION['user_id'])) {
    header('Location: login.php');
    exit();
}

// Get filter parameters
$format = $_GET['format'] ?? 'excel';
$date_from = $_GET['date_from'] ?? date('Y-m-d', strtotime('-30 days'));
$date_to = $_GET['date_to'] ?? date('Y-m-d');
$log_type = $_GET['log_type'] ?? 'all';
$user_id = $_GET['user_id'] ?? 'all';
$entity_type = $_GET['entity_type'] ?? 'all';
$status = $_GET['status'] ?? 'all';
$search = $_GET['search'] ?? '';

try {
    // Build filters array
    $filters = [
        'date_from' => $date_from,
        'date_to' => $date_to,
        'log_type' => $log_type,
        'user_id' => $user_id,
        'entity_type' => $entity_type,
        'status' => $status,
        'search' => $search
    ];
    
    // Get logs
    $logs = get_activity_logs($filters, 0, 0); // 0 means no limit
    
    // Get user info for report header
    $user_stmt = $pdo->prepare("SELECT first_name, last_name, email FROM users WHERE user_id = ?");
    $user_stmt->execute([$_SESSION['user_id']]);
    $user = $user_stmt->fetch();
    
    // Log the export activity
    log_activity(
        'export',
        $_SESSION['user_id'],
        'Report',
        null,
        'Activity Logs Report',
        'Exported activity logs report in ' . strtoupper($format) . ' format',
        null,
        null,
        'Success',
        $_SERVER['REMOTE_ADDR'] ?? '127.0.0.1',
        $_SERVER['HTTP_USER_AGENT'] ?? ''
    );
    
    if ($format == 'excel') {
        exportToExcel($logs, $date_from, $date_to, $user);
    } else {
        exportToPDF($logs, $date_from, $date_to, $user);
    }
    
} catch (PDOException $e) {
    error_log("Export error: " . $e->getMessage());
    die("Error generating report. Please try again.");
}

function exportToExcel($logs, $date_from, $date_to, $user) {
    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment; filename="activity_logs_' . date('Ymd_His') . '.xls"');
    
    echo "<table border='1'>";
    echo "<tr><th colspan='9' style='background:#1f366c;color:white;font-size:16px;padding:10px;'>ACTIVITY LOGS REPORT</th></tr>";
    echo "<tr><td colspan='9'><strong>Generated by:</strong> " . htmlspecialchars($user['first_name'] . ' ' . $user['last_name']) . 
         " | <strong>Date Range:</strong> " . htmlspecialchars($date_from) . " to " . htmlspecialchars($date_to) . 
         " | <strong>Total Logs:</strong> " . count($logs) . "</td></tr>";
    echo "<tr style='background:#f2f2f2;font-weight:bold;'>";
    echo "<th>Log ID</th><th>Timestamp</th><th>User</th><th>Action Type</th><th>Entity</th><th>Description</th><th>Status</th><th>IP Address</th><th>Created At</th>";
    echo "</tr>";
    
    foreach ($logs as $log) {
        echo "<tr>";
        echo "<td>L" . str_pad($log['log_id'], 5, '0', STR_PAD_LEFT) . "</td>";
        echo "<td>" . htmlspecialchars($log['created_at']) . "</td>";
        echo "<td>" . htmlspecialchars($log['first_name'] . ' ' . $log['last_name']) . "</td>";
        echo "<td>" . htmlspecialchars($log['log_type']) . "</td>";
        echo "<td>" . htmlspecialchars($log['entity_type'] . ($log['entity_name'] ? ': ' . $log['entity_name'] : '')) . "</td>";
        echo "<td>" . htmlspecialchars(substr($log['action_description'], 0, 100)) . (strlen($log['action_description']) > 100 ? '...' : '') . "</td>";
        echo "<td>" . htmlspecialchars($log['status']) . "</td>";
        echo "<td>" . htmlspecialchars($log['ip_address']) . "</td>";
        echo "<td>" . htmlspecialchars($log['created_at']) . "</td>";
        echo "</tr>";
    }
    
    echo "</table>";
    exit;
}

function exportToPDF($logs, $date_from, $date_to, $user) {
    // Simple HTML that can be saved as PDF
    header('Content-Type: application/pdf');
    header('Content-Disposition: attachment; filename="activity_logs_' . date('Ymd_His') . '.pdf"');
    
    $html = "<h1>ACTIVITY LOGS REPORT</h1>";
    $html .= "<p><strong>Generated by:</strong> " . htmlspecialchars($user['first_name'] . ' ' . $user['last_name']) . "</p>";
    $html .= "<p><strong>Date Range:</strong> " . htmlspecialchars($date_from) . " to " . htmlspecialchars($date_to) . "</p>";
    $html .= "<p><strong>Total Logs:</strong> " . count($logs) . "</p>";
    
    $html .= "<table border='1' cellpadding='5' cellspacing='0' style='width:100%;border-collapse:collapse;font-size:10px;'>";
    $html .= "<tr style='background:#f2f2f2;font-weight:bold;'>";
    $html .= "<th>Log ID</th><th>Timestamp</th><th>User</th><th>Action</th><th>Entity</th><th>Status</th></tr>";
    
    foreach ($logs as $log) {
        $html .= "<tr>";
        $html .= "<td>L" . str_pad($log['log_id'], 5, '0', STR_PAD_LEFT) . "</td>";
        $html .= "<td>" . htmlspecialchars(date('Y/m/d H:i', strtotime($log['created_at']))) . "</td>";
        $html .= "<td>" . htmlspecialchars($log['first_name'] . ' ' . $log['last_name']) . "</td>";
        $html .= "<td>" . htmlspecialchars($log['log_type']) . "</td>";
        $html .= "<td>" . htmlspecialchars($log['entity_type']) . "</td>";
        $html .= "<td>" . htmlspecialchars($log['status']) . "</td>";
        $html .= "</tr>";
    }
    
    $html .= "</table>";
    
    echo $html;
    exit;
}
?>